### ISSUE TITLE
Issue in opening the Application

### ISSUE THREAD

**Issue by sarfarazengglb** [t-higuchi/iperf3-android#1]
Hi,
I was able to build and generate the.apk file however the application is failing in startup with below error.
02-21 13:25:35.662 7842-7842/jp.empacket.iperf3 E/AndroidRuntime: FATAL EXCEPTION: main
                                                                  Process: jp.empacket.iperf3, PID: 7842
                                                                  java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/jp.empacket.iperf3-1/base.apk"],nativeLibraryDirectories=[/data/app/jp.empacket.iperf3-1/lib/x86, /system/fake-libs, /data/app/jp.empacket.iperf3-1/base.apk!/lib/x86, /system/lib, /vendor/lib]]] couldn't find "libnative-lib.so"
                                                                      at java.lang.Runtime.loadLibrary0(Runtime.java:972)
                                                                      at java.lang.System.loadLibrary(System.java:1530)
                                                                      at jp.empacket.iperf3.MainActivity.<clinit>(MainActivity.java:11)
                                                                      at java.lang.Class.newInstance(Native Method)
                                                                      at android.app.Instrumentation.newActivity(Instrumentation.java:1078)
                                                                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2538)
                                                                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2707)
                                                                      at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1460)
                                                                      at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                      at android.os.Looper.loop(Looper.java:154)
                                                                      at android.app.ActivityThread.main(ActivityThread.java:6077)
                                                                      at java.lang.reflect.Method.invoke(Native Method)
                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866)
                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756)

=======================================================
I tried changing the defaultConfig and other but no luck.

  ndk {
            abiFilters "armeabi-v7a", "x86", "armeabi", "mips"
        }

**Comment by sarfarazengglb** [comment]
I solved it you are building iperf so but in your code you are loading native-lib this will make issue.

**Comment by sarfarazengglb** [comment]
I solved it you are building iperf so but in your code you are loading native-lib this will make issue.

**Comment by sarfarazengglb** [comment]
It is  solved you are building iperf so but in your code you are loading native-lib this will make issue.

**Comment by victors0991** [comment]
Hello I solve the problem but it appear black page with one label text. I expect that appear a user interface and run program
 How do I run program?
